### ISSUE TITLE
Thank you very much!!!

### ISSUE THREAD

**Issue by colinskow** [osechet/angular-tour-of-heroes-webpack#1]
@osechet I took some of your Electron configuration code and this helped me solve some of the fundamental hurdles to creating the ideal Angular/Electron development workflow.

I've now got HMR working directly in Electron, native Karma unit tests running in Electron, and E2E using Spectron.

Feel free to check out my project and let me know if you have any ideas.
https://github.com/colinskow/angular-electron-dream-starter

Cheers,
- Colin

(you can close this issue once you've seen it.)

**Comment by osechet** [comment]
@colinskow Glad to see it helped you. I'll probably have a look to your solution later when I'll have time.
